// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistant;

#nullable disable

namespace Persistant.Migrations
{
    [DbContext(typeof(RepositoryDbContext))]
    [Migration("20251122045308_AddRefreshtokenColumnInPersonTable")]
    partial class AddRefreshtokenColumnInPersonTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.BaseEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("Domain.Entities.Person", b =>
                {
                    b.HasBaseType("Domain.Entities.BaseEntity");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("Roles")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasFilter("[Username] IS NOT NULL");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("Domain.Entities.PersonTaskItem", b =>
                {
                    b.HasBaseType("Domain.Entities.BaseEntity");

                    b.Property<Guid>("AssignedToId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TaskItemId")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("AssignedToId");

                    b.HasIndex("TaskItemId");

                    b.ToTable("PersonTaskItems");
                });

            modelBuilder.Entity("Domain.Entities.PersonTaskItemGroup", b =>
                {
                    b.HasBaseType("Domain.Entities.BaseEntity");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PersonRole")
                        .HasColumnType("int");

                    b.Property<Guid>("TaskItemGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("PersonId");

                    b.HasIndex("TaskItemGroupId");

                    b.ToTable("PersonTaskItemGroup");
                });

            modelBuilder.Entity("Domain.Entities.TaskItem", b =>
                {
                    b.HasBaseType("Domain.Entities.BaseEntity");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("EditedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("TaskGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("CreatedById");

                    b.HasIndex("EditedById");

                    b.HasIndex("TaskGroupId");

                    b.ToTable("TaskItems");
                });

            modelBuilder.Entity("Domain.Entities.TaskItemGroup", b =>
                {
                    b.HasBaseType("Domain.Entities.BaseEntity");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("CreatedById");

                    b.ToTable("TaskItemGroups");
                });

            modelBuilder.Entity("Domain.Entities.TaskItemNote", b =>
                {
                    b.HasBaseType("Domain.Entities.BaseEntity");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TaskItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("CreatedById");

                    b.HasIndex("TaskItemId");

                    b.ToTable("TaskItemNotes");
                });

            modelBuilder.Entity("Domain.Entities.PersonTaskItem", b =>
                {
                    b.HasOne("Domain.Entities.Person", "AssignedTo")
                        .WithMany("AssignedTasks")
                        .HasForeignKey("AssignedToId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.TaskItem", "TaskItem")
                        .WithMany("PersonTasks")
                        .HasForeignKey("TaskItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedTo");

                    b.Navigation("TaskItem");
                });

            modelBuilder.Entity("Domain.Entities.PersonTaskItemGroup", b =>
                {
                    b.HasOne("Domain.Entities.Person", "Person")
                        .WithMany("Groups")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.TaskItemGroup", "TaskItemGroup")
                        .WithMany("PersonGroups")
                        .HasForeignKey("TaskItemGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");

                    b.Navigation("TaskItemGroup");
                });

            modelBuilder.Entity("Domain.Entities.TaskItem", b =>
                {
                    b.HasOne("Domain.Entities.Person", "CreatedBy")
                        .WithMany("CreatedTasks")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Person", "EditedBy")
                        .WithMany("EditedTasks")
                        .HasForeignKey("EditedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Entities.TaskItemGroup", "TaskGroup")
                        .WithMany("Tasks")
                        .HasForeignKey("TaskGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("EditedBy");

                    b.Navigation("TaskGroup");
                });

            modelBuilder.Entity("Domain.Entities.TaskItemGroup", b =>
                {
                    b.HasOne("Domain.Entities.Person", "CreatedBy")
                        .WithMany("CreatedGroups")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("Domain.Entities.TaskItemNote", b =>
                {
                    b.HasOne("Domain.Entities.Person", "CreatedBy")
                        .WithMany("CreatedNotes")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.TaskItem", "TaskItem")
                        .WithMany("Notes")
                        .HasForeignKey("TaskItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("TaskItem");
                });

            modelBuilder.Entity("Domain.Entities.Person", b =>
                {
                    b.Navigation("AssignedTasks");

                    b.Navigation("CreatedGroups");

                    b.Navigation("CreatedNotes");

                    b.Navigation("CreatedTasks");

                    b.Navigation("EditedTasks");

                    b.Navigation("Groups");
                });

            modelBuilder.Entity("Domain.Entities.TaskItem", b =>
                {
                    b.Navigation("Notes");

                    b.Navigation("PersonTasks");
                });

            modelBuilder.Entity("Domain.Entities.TaskItemGroup", b =>
                {
                    b.Navigation("PersonGroups");

                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
